### PR TITLE
Update imports for react native 0.40

### PR DESCRIPTION
**Pull request by stevenremot**
This PR updates the imports to the react native libraries to be compatible with RN 0.40 .

This is a breaking change that will make the library incompatible with projects using RN < 0.40 .

More information at https://github.com/facebook/react-native/releases/tag/v0.40.0

### CODE REVIEW

**Comment by BWJesseR** [comment]
@skycocker can this be merged? With React 0.48 if this isn't included you cannot compile.

**Review by keshk26 — APPROVED** [review]

**Comment by keshk26** [comment]
Could you please merge this PR for the latest react native version?

**Comment by skycocker** [comment]
Sure. Sorry for the delay. Thanks!

**Comment by BWJesseR** [comment]
Could you also bump the version number? 😄

**Pull request merged**
