### PR TITLE
Updated listeners to return EmitterSubscription object.

### PR DESCRIPTION
**Pull request by adamivancza**
This way we can unsubscribe directly as we don't need to care about the callback function. Source: https://stackoverflow.com/a/36901160/851490

### CODE REVIEW

**Comment by skycocker** [comment]
does this even work? it doesn't look like there is a `subscription` object set anywhere.

**Comment by adamivancza** [comment]
it should be used like this:

`const subscription = RCTSFSafariViewController.addEventListener('onDismiss', () => {});`

then later you can call 
`RCTSFSafariViewController.removeEventListener(subscription);`

**Comment by skycocker** [comment]
ok then - but could you update readme as well? :)

**Comment by adamivancza** [comment]
done :)

**Comment by skycocker** [comment]
merged. Thanks! :)

**Pull request merged**
